baseURL = "https://moniquelive.com"
languageCode = "pt-br"
title = "Monique Oliveira"
theme = "ananke"
disqusShortname = "moniquelive-com"

DefaultContentLanguage = "pt-br"
SectionPagesMenu = "main"
Paginate = 9
googleAnalytics = "UA-129884631-1"
enableRobotsTXT = true
enableEmoji = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "favicons/favicon.ico"
  description = "Um ser humano em busca de si mesmo."
  facebook = "https://www.facebook.com/cyberleo"
  twitter = "https://twitter.com/moniquelive"
  instagram = "https://www.instagram.com/monique.live/"
  youtube = "https://www.youtube.com/channel/UCML4uqYh36vkI0UTTGBxByg"
  github = "https://github.com/lccro"
  # gitlab = "https://gitlab.com/lccro"
  linkedin = "https://www.linkedin.com/in/leolive/"
  # mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-pink"
  body_classes = "helvetica bg-near-white"
  featured_image = "/images/background.jpg"
  recent_posts_number = 2
  custom_css = ["css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
