baseURL: "https://moniquelive.com"
languageCode: pt-br
DefaultContentLanguage: pt-br

title: Monique Oliveira
theme: dream
ignoreErrors:
  - error-remote-getjson

googleAnalytics: UA-129884631-1
DisqusShortname: moniquelive-com
enableRobotsTXT: true

SectionPagesMenu: main
Paginate: 9
enableEmoji: true

markup:
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml

params:
  title: Monique Oliveira
  favicon: favicons/favicon.ico
  description: Uma ser humana em busca de si mesma.
  author: moniquelive
  avatar: /images/me.jpg
  motto: Uma ser humana em busca de si mesma.

  # youtube: "https://www.youtube.com/channel/UCML4uqYh36vkI0UTTGBxByg"
  facebook: cyberleo
  twitter: moniquelive
  instagram: monique.live
  github: lccro
  linkedin: moniquelive
  stackoverflow: 9793/cyber-oliveira
  siteStartYear: 2018

  # dark mode
  darkLinkColor: "#f77"
  darkNav: true
  dark404Button: true

  background: "#333"
  # backgroundImage: /images/background.jpg

taxonomies:
  category: categories
  series: series
  tag: tags
